
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export type AUTHENTICATING_USER = typeof AUTHENTICATING_USER;

export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export type AUTHENTICATE_USER_SUCCESS = typeof AUTHENTICATE_USER_SUCCESS;

export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export type AUTHENTICATE_USER_FAILED = typeof AUTHENTICATE_USER_FAILED;

export const LOGOUT = 'LOGOUT';
export type LOGOUT = typeof LOGOUT;

export const SIGNUP_USER = 'SIGNUP_USER';
export type SIGNUP_USER = typeof SIGNUP_USER;

export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export type SIGNUP_USER_SUCCESS = typeof SIGNUP_USER_SUCCESS;

export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';
export type SIGNUP_USER_FAIL = typeof SIGNUP_USER_FAIL;
